# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Week4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Week4
  pod 'Alamofire'
  pod 'Kingfisher'

  target 'Week4Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Week4UITests' do
    # Pods for testing
  end

end
